services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  bluesky-verifier:
    build: .
    environment:
      - BSKY_HANDLE=your-handle.bsky.social
      - BSKY_APP_PASSWORD=your-app-password
      - POST_URI=at://example.bsky.social/app.bsky.feed.post/xxxxx
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

volumes:
  redis-data:
